- name: play3
  hosts:  web_servers
  vars_files: ./vars.yml
  tasks:
    - name: installing a webserver
      apt:
          name: "{{ item.pkg_name }}"
          state: "{{ item.pkg_version }}"
      loop: "{{ packages }}"

    - name: installing a webserver
      apt:
        name: nginx
        state: restarted
      when: ansible_facts['distribution'] == "Ubuntu"
      register: task_result

    - name: installing httpd
      yum:
        name: httpd
        state: restarted
      when: ansible_facts['distribution'] == "CentOS"
      register: task_result

    - name: debugging 
      debug:
          var: task_result

    - name: debugging service 
      service:
        name: myservice
        state: restarted
      when: task_result.changed or not task_result.failed