- name: play_loops
  hosts:  web_servers
  vars_files: ./vars.yml
  tasks:
    - name: installing a webserver
      apt:
        name: "{{ item.pkg_name }}"
        state: "{{ item.pkg_version }}"
      loop: "{{ packages }}"


