- name: play1
  hosts:  web_servers

  tasks:

    - name: installing a webserver
      apt:
        name: "{{ item }}"
        state: latest
      loop:
        - nginx
        - curl
        - sudo
        - ssh


