- name: play4
  hosts:  web_servers

  vars:
    msg: "Hello Ansible from template"

  tasks:
    - name: template example
      template:
        src: test_template.j2
        dest: /var/www/html/index.html