---
- name: Test Vars
  hosts: web_servers
  gather_facts: False
  vars: 
    dir_name: test

  tasks:
    - name: Update apt cache
      tags: update
      apt:
        update_cache: True
    
    - name: Install the latest version of Apache
      tags: install
      yum:
        name: httpd
        state: latest
    
    - name: copy index file
    
      copy: 
        src: ./index.html
        dest: /var/www/html/index.html
    

