---
- name: playbook-day2
  hosts: web_servers
  gather_facts: False

  tasks:
    - name: apt update
      apt:
        update_cache: True

    - name: copy index file
      copy: 
        src: ./index.html
        dest: /var/www/html/index.html
          
    - name: Restarting the web-server
      sysvinit: 
        name: nginx
        state: restarted