---
- name: Test Vars
  hosts: localhost #web_servers
  gather_facts: False
  become: True
  vars:
    p_name: pkg_name
    p_version: pkg_version
    u_cache: cache
    
  tasks:
  - name: Update apt cache
    apt:
      update_cache: "{{ u_cache }}"
      
  - name: Install the latest version of Apache
    apt:
      name: "{{ p_name }}"
      state: "{{ p_version }}"
        
