---
- name: Test Vars
  hosts: web_servers
  gather_facts: False
  vars: 
    dir_name: test

  tasks:
    - name: Update apt cache
      tags: update
      apt:
        update_cache: True
    
    - name: create dir
      file:
         path: "{{ dir_name }}"
         state: directory

    - name:
      command: "ls {{ dir_name }}"
      register: results

    - name: print stdout
      debug:
          var: results.stdout


    - name: Install the latest version of Apache
      tags: install
      apt:
        name: httpd
        state: latest
    
    - name: copy index file
      copy: 
        src: ./index.html
        dest: /var/www/html/index.html
    

